trigger:
- master

name: Azure Pipelines
variables:
  python.version: '3.7.6'

jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: 'ENV-TEST'
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo 'hello world! This my first VM'